# Managed by cyberforce-speedrun.
# Debian processes sshd_config.d files before later sshd_config directives.
Port 22
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys

Match User ssh-user
    PasswordAuthentication no
    KbdInteractiveAuthentication no
Match all
